const Controller = require('egg').Controller;

class HomeController extends Controller {
  async index() {
    // let global_access_token = await this.ctx.app.mysql.query("update weixin set value='',expire_timestamp='' where  my_key='global_access_token';");
    // this.ctx.body = await this.ctx.service.record.indexConverter();
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 5, 12, 1507796683000, "我要干嘛?", "人的需求是变来变去的,马斯洛累/休息/食物/水/生理. 满足之后才会寻找更高的追求!   所以我应该保障满足自己的基本需求再去追求 情感/尊重/自我实现!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 5, 12, 1507800920000, "应该寻找怎样的爱情?", "不管出于什么目的, 是不会导致特定结果的!例如: 我想明年找个女朋友, 不会导致吵架/离婚/分手/忍受/伤心/痛苦、以及ML/公开关系/结婚/生孩/开心/经历. 这些结果不是因为你的目的能够规避的.明确好需求。选出你想要的，规避你不想要的才是最重要的！影响这些结果因素最大的往往是认知程度（思维）");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 6, 13, 1507902184000, "默认标题", "我是一个很容易受到感动的人！看到别人做的APP，动画，剧情，自己就想去做一个！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 6, 13, 1507902298000, "请不要纠结于看书！", "学习不是读书/阅读. 读书/阅读只是学习的[接触与提问]前半段, 结合后半段[思考与总结]才是真正的学习! 学以致用, 不要错把过程当目标了!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 6, 13, 1507903735000, "默认标题", "一次应该只专心做一件事！不然精力消耗实在太快！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 6, 13, 1507908206000, "默认标题", "不要去追求github上传数，这些表面上的东西太虚了！实际上是并没有产生价值！追求这些容易让自己浮躁！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507949193000, "观念会不会阻碍你变得富有？  ", "成功最求财富的因素有很多，但是观念不是影响你追求财富的最大因素！勤奋努力才是。当然观念正确与认知程度高总归是比较好的！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507950389000, "默认标题", "出去玩，到了中午一定要找个地方休息。（麦当劳也好）因为是去玩，满足基本需求，人才会快乐！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507952514000, "现在马上要给你答复吗？", "思绪没有理清楚，就要想清楚。比较重要的事情就不要急，没什么紧要的！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507952605000, "如何判断自己状态如何？？", "专注一件事，然后看看你会不会想去看看微信？");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507953562000, "默认标题", "我的JavaScript一定会非常精通！代码一定会写的非常的好！后端应用程序一定会去学一定能够做到的！因为有时间！因为祖国繁荣昌盛！任谁不相信一个认真努力的人会一直穷下去的！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507953785000, "朋友圈的作用", "拍照的意义在于拿出来分享，当和人一起时可以拿出来作为谈资！就可以快速理解带入，不然光凭语言是很空白的！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507954229000, "MySQL数据库总结", "突然想做一件事, 那就去认真做, 总会有收获的! 即使之后发现不可能成功, 那也是因为你去做了才发现不可能成功的.没去做之前根本就不知道能不能成功.");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507954493000, "默认标题", "高考美术 - 游戏原画 - 自由漫画 - 自由插画师：不错不错，我喜欢。什么？画功是什么？？");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507954983000, "债务与积累", "积累财富最重要的不仅仅是自身技能与能力有多强（这也很重要！）是要依赖一点点的积累！是当自身的资产大于债务的时候。所以生活方式也不应该那么浮夸，人家老干部作风才是优良！这些才是精英！不要学那些电视剧里面的！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507955040000, "默认标题", "有些东西不改变，那以后也不会有改变。所以当有矛盾的时候，就想一定要记录下来去解决！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507956922000, "明白自己真正需要什么很重要！", "比如说你想要一套房子。其中就暗含了 fortune freedom and health，而这就是 wealth 的构成。");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 2, 7, 14, 1507977072000, "为什么要需要爱情?", "因为当你拥有房子，游戏，书刊，美食等满足你爱好各种设施。但是你身边没有人和你沟通交流。这对你的心理是不健康的。所以需要亲密的关系。所以寻求爱情应该以这个方向去努力！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 3, 1, 15, 1508070610000, "危机意识版的五个点之基本", "表现以及引导思维积极可以促进自己并且影响他人良性循环");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 3, 1, 15, 1508072532000, "这个时候我应该做啥？", "1.要找女友成立家庭了（至少也要往那方面去努力努力）有了家庭以后生活才会健康！2.事业上要多赚钱，以后才能生活的顺利！以后有了孩子，有房子，多去旅游3.画什么时候画都可以，游戏可以作为一枚月亮与六便士，感动时候感动就很好！追求也是一种体验！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 3, 1, 15, 1508079340000, "默认标题", "一些打麻将老太太，我们会觉得她格局小。因为他们专注于一些鸡毛蒜皮的小事情上面。一些老干部，我们就不会这么觉得！因为他们有着对社会有着他们的贡献！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 3, 2, 16, 1508135657000, "为什么不学习Node.js而去学习JAVA呢?", "学习 MySQL MongoDB 设计模式 Java 热不热门 道理蕴涵 思考 总结");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 3, 2, 16, 1508141954000, "我应该抱着什么目的去学习?", "应该是抱着发挥其价值的目的去学！不然迟早学不下去!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 3, 3, 17, 1508251399000, "如何让一个东西井然有序？", "这不是你一开始就能够规划好的！这需要你不断的进行整理");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 3, 5, 19, 1508342428000, "默认标题", "文字是触发联想的机制，所以并不一定需要一段话！可以是一堆词汇！当你在思考时候，往往想着如何表达，思维就断了！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 3, 5, 19, 1508344198000, "期盼不应太大", "书，思考生活 思考 帮助 意义不得而知知乎 思考 习惯游戏 直播放松 同理");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 2, 23, 1508723055000, "你想要怎样的生活?", "女朋友 沟通 房子光线厚涂思考 读书 电影 游戏 体验");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 2, 23, 1508723159000, "淘金思维", "思考 不断的追溯下去最终涉及 都是 关于人生意义!所以  多追溯自己的目标是什么?这是值得你去思考的!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 2, 23, 1508723218000, "保持思维通畅", "不打断思维，就会有源源不断的想法出现! 精神状态 思维积极");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 4, 25, 1508911281000, "默认标题", "海鹏辞职, 叔叔7000k, 租房前端8000k , 受影响");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 4, 25, 1508911532000, "为了完成一项金融网站的任务, 你还有什么不足? 你还需要准备什么?  ", "目标   语言 技巧？准确，稳定，高效，易拓展，易维护。语言 深入 熟练 不断看书github trend");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 4, 25, 1508913002000, "函数式编程?", "当你对一个东西不了解时候，难免期望过高 !");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 4, 25, 1508915941000, "默认标题", "基础(思想) + 经验(熟悉) + 时间/精力 = 好代码!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 6, 27, 1509072001000, "记得多回顾", "干活中 记录 不同概念  一心二用 正确应该是专心 之后再回顾");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 6, 27, 1509075682000, "正确的心态应该是", "后悔 表白 误解 冲锋号角 说的好像 既然事情已经这样了, 让我们想想能够做些啥?");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 6, 27, 1509077185000, "我应该干嘛?", "很清晰 回答 从本质出发 按需求来");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 6, 27, 1509088003000, "努力 成功 这种信念!", "自古历史从来没有这种规律! 民国抗日战争是如此，建国改革开放也是如此 ! 从来都是既然事情已经这样了, 让我们想想能够做些啥?");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 7, 28, 1509181812000, "收集勾起自己学习的欲望清单!", "收集自己的学习的欲望清单就好比相亲 必须不断尝试才能找到最适合自己的一个!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 7, 28, 1509181839000, "记忆力差", "所以笔记才是针对我学习的方法. 请认清这一点并且有效加以利用! 精益求精! 这才能掌握学习的方法!躺着单独思考是最利于我记忆的!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 7, 28, 1509181850000, "一旦累了就很难坚持!", "越强迫自己, 就越厌恶. 那不如找一个不排斥的方法! 消除这种情绪!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 7, 28, 1509181906000, "默认标题", "比起从基础一点点来, 做出成果是最适合我的!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 7, 28, 1509184246000, "所谓的成功学", "成功 = 行动 + 结果意思就是说...既然事情已经这个吊样了(结果)，让我们看看还能做些什么？(行动)");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 1, 29, 1509259860000, "默认标题", "不好好赚钱，就是去到景区，连雨衣都不想买");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 1, 29, 1509268534000, "学习金字塔", "信息留存率讨论、实践、输出");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 2, 30, 1509365628000, "默认标题", "爱情不是雪中送炭，只是锦上添花。所以你要做到一个人也要好好的如果没,有就既然事情因为这样了! 只能努力去找!如果有,那就要做到锦上添花！爱情重要的一点是解决沟通的需求");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (10, 4, 3, 31, 1509421389000, "默认标题", "寻求更好的工作机会应该是现阶段一直努力的事!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 2, 4, 8, 1510131729000, "默认标题", "在脑子不好使的时候，脑部产生阅读障碍。此时就要把句子拆分成 主、谓、宾、来食用。");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 2, 4, 8, 1510131029000, "默认标题", "内在心理是害怕被嘲笑, 保护机制作用.");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 2, 4, 8, 1510133389000, "默认标题", "其实 表达 词汇 省去 主谓宾");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 2, 4, 8, 1510130504000, "默认标题", "为什么会有厌烦情绪? 因为短时间积压了非常多的问题.");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 2, 4, 8, 1510130722000, "默认标题", "聚餐只是解决沟通的需求表达 影响 联想 体验");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 2, 1, 12, 1510473841000, "默认标题", "不动动脑子，MySQL各种框架技术践 这种东西真的很难学...");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 2, 1, 12, 1510474204000, "猜测", "文档看不懂, 你 可以依赖  (猜测 <——> 验证) 这样的过程 进行 学习。");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 3, 7, 18, 1510982876000, "不思考会变蠢?", "按照 惯性 思考 不如 不思考");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 3, 7, 18, 1510999602000, "默认标题", "我 不能 边思考 边记录我应该 思考完成，再进行记录我应该专心做一件事思考 和 记录 是 两件事");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (11, 3, 7, 18, 1511017949000, "默认标题", "(周末)我 应该健康看电影(周末)我 应该健康玩游戏(周末)我 应该好好的思考(周末)我 应该好好的休息(周末)我 应该积极的生活(周末)我 应该去记忆 一些自己的结论");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (12, 1, 1, 3, 1512300732000, "无聊应该做啥?", "很多事情还没想通，还可以做的更好！很多东西还没体验应该把时间投入到这些里面去");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (12, 2, 6, 8, 1512730675000, "默认标题", "没有价值的东西是不会去做的");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (12, 2, 7, 9, 1512791165000, "默认标题", "周末 不想做就躺下来思考，直到想做为止、");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (12, 2, 7, 9, 1512791306000, "默认标题", "不想做 因为没有明确目标");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (12, 2, 2, 11, 1513003262000, "默认标题", "真正提升的 是 百度前端技术学院 ant");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (12, 4, 4, 27, 1514347569000, "默认标题", "工作是一辈子要工作的！劳动力的问题，以后老了估计都要劳动～开心和幸不幸福是自己能够争取的！多读书");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (12, 4, 5, 28, 1514432151000, "默认标题", "应该提升自己的代码，多造轮子，多改版首页。应该多看书才对！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (1, 1, 3, 2, 1514858143000, "设计参考", "Ant Design  Element UI  微信公众平台  微信 WeUI");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (1, 1, 5, 4, 1514996148000, "默认标题", "休息好, 让自己闲下来就发现 想做的事情越积越多.. 还是不要搞事胡乱提需求. 还是应该忘怀好!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (1, 1, 5, 4, 1514999757000, "默认标题", "工资偏低 - 因为找工作是十分麻烦的事情 - 麻不麻烦不重要 - 核心矛盾点 - 工资低 牵扯到其他方面 - 特别复杂兼巨大 - 但是这都不是重点");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (1, 1, 5, 4, 1515033285000, "默认标题", "显式传递上下文对象会让代码变得越来越混乱， 使用 this因此可以将 API 设计 得更加简洁并且易于复用!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (1, 1, 5, 4, 1515035360000, "默认标题", "5分钟原则, 需要完成的任务迟迟不肯开始? ok, 先做5分钟试试.");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (1, 1, 5, 4, 1515050995000, "默认标题", "代码好不好，要看数据好不好追溯!");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (1, 4, 5, 25, 1516880641000, "默认标题", "以后想学手绘，可以画B站的 2233看版娘");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (1, 4, 5, 25, 1516880682000, "默认标题", "有需要放空思维");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (2, 1, 6, 2, 1517543359000, "默认标题", "git push origin master");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (2, 3, 3, 20, 1519097404000, "默认标题", "生活中 矛盾点，抓住 深入 思考。");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (2, 3, 3, 20, 1519097446000, "默认标题", "看视频是一种放松， 我需要其他放松方式");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (2, 4, 1, 25, 1519525670000, "默认标题", "累必要 - 脑袋放空 充沛 - 思维发散 意志力 - 专注一件事");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (2, 4, 1, 25, 1519555136000, "默认标题", "强制放松 不如 跑思维逻辑 闭上眼睛 仅思考 专注 ");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (2, 4, 1, 25, 1519571832000, "默认标题", "不理你 说明 不重要 本来就是 没什么不好承认的，这是事实期盼 孤独 寂寞 女朋友 需要 追求 以及其它方面各种 亲密关系");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (3, 1, 7, 3, 1520019149000, "默认标题", "知乎英语总结的方法不错以后抓住点应当多多总结方法才对！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (3, 1, 3, 6, 1520347871000, "玻璃球测临界点问题《动态规划》", "有一栋100层高的大楼，给你两个完全相同的玻璃球。假设从某一层开始，丢下玻璃球会摔碎。请用最少步数测出小球破裂高度的最小次数。 <a>谷歌面试题——玻璃球测临界点问题</a><a>用2个玻璃球找到从一100层的大楼的某一层落下刚好会摔碎，如何制定最优策略？</a>");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (3, 2, 6, 9, 1520607647000, "默认标题", "想事情 要闭眼睛想只要什么都不想，就会有思考旅游也是如此，才会有体验！");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (3, 2, 7, 10, 1520611353000, "默认标题", "又看微信去了 说明累 还有其他 思维 体验保持思维通畅");');
// await this.ctx.app.mysql.query('INSERT INTO `record_list_2018` (`record_month`, `record_week`, `record_day`, `record_data`, `timestamp`, `title`, `content`) VALUES (4, 3, 6, 20, 1524197670000, "禅道", "主要作用是为了反馈进度，而不是为了造假！");');
this.ctx.body = 'Hello ~~~ Welcome to Rejiejay server side and your place in home';
    // this.ctx.body = await this.ctx.service.record.save(12, 2018, '331','331');
    // this.ctx.body = await this.ctx.app.mysql.query(`select record_amount from record_index_${2018} where month_count="0" and week_count="0";`);
  }

  async post() {
    console.log('接收到post 请求');
  }
}

module.exports = HomeController;
